# Site settings
title:       Marlon Wiebe
blogtitle:   Marlon Makes
email:       mr.m.wiebe@gmail.com
author:      Marlon Wiebe
description: "A place where I can put things I've learned and figured out so I don't hafta worry about remembering how I did that thing a long time ago. :)"
baseurl:     ""
url:         "http://mrmwiebe.github.io"
date_format: "%b %-d, %Y"
paginate_path: "/blog/page:num/"

# Google services
google_analytics:   'UA-47397211-2'
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   marlonmakes

# Social icons
twitter_username:   mr_m_wiebe
vimeo_username:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /blog/posts/:title
paginate:     4
sass:
  compressed: true
